baseURL = "/"
languageCode = "en-ie"
title = "Cooklang: recipe markup language"
themesDir = "./themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30
# sectionPagesMenu = "main"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "CLI"
    url = "/cli/"
    weight = 3

[[menu.main]]
    name = "Mobile App"
    url = "/app/"
    weight = 4

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5


[params]
  google_analytics_id="G-5XEMVMR4NG"
  # homepage_button_link = '/docs'
  # homepage_button_text = 'Read The Docs'
  # homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  # homepage_image = '/images/terminal.gif'
  mainSections = ["docs", "cli", "app", "blog"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Cooklang is a markup language for recipes."
    meta_og_title = "Cooklang â€“ Recipe Markup Language"
    meta_og_type = "website"
    meta_og_url = "https://cooklang.org"
    meta_og_image = "https://cooklang.org/example.png"
    meta_og_description = "Cooklang is a markup language for recipes."
    # meta_twitter_card = "summary"
    # meta_twitter_site = "@Cooklang"
    # meta_twitter_creator = "@Cooklang"

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"
